#define BMS_HEARTBEAT_ID 1536
#define BMS_HEARTBEAT_FREQ 1
#define __DEVICE_ID_start 0
#define __DEVICE_ID_end 31
#define ____DEVICE_ID_from 0
#define ____DEVICE_ID_to 4294967295
#define __SERIAL_NO_start 32
#define __SERIAL_NO_end 63
#define ____SERIAL_NO_from 0
#define ____SERIAL_NO_to 4294967295

#define TI_PACKET_ID 769
#define TI_PACKET_FREQ 100
#define __ACC_VAL_start 0
#define __ACC_VAL_end 7
#define ____ACC_VAL_from 0
#define ____ACC_VAL_to 255
#define __BRAKE_VAL_start 8
#define __BRAKE_VAL_end 15
#define ____BRAKE_VAL_from 0
#define ____BRAKE_VAL_to 255
#define __FLAGS_start 16
#define __FLAGS_end 23
#define ____FLAGS_from 0
#define ____FLAGS_to 255

#define WHEEL_VELOCITY_1_ID 1795
#define WHEEL_VELOCITY_1_FREQ 5
#define __WHEEL_VELOCITY_1_start 0
#define __WHEEL_VELOCITY_1_end 15
#define ____WHEEL_VELOCITY_RPM_from 0
#define ____WHEEL_VELOCITY_RPM_to 65535

#define WHEEL_VELOCITY_2_ID 1796
#define WHEEL_VELOCITY_2_FREQ 5
#define __WHEEL_VELOCITY_2_start 0
#define __WHEEL_VELOCITY_2_end 15
#define ____WHEEL_VELOCITY_RPM_from 0
#define ____WHEEL_VELOCITY_RPM_to 65535

#define DI_PACKET_ID 1285
#define DI_PACKET_FREQ 10
#define __KEY_IGNITION_start 0
#define __KEY_IGNITION_end 15
#define ____RUN 32
#define ____START 64
#define __DRIVE_STATUS_start 16
#define __DRIVE_STATUS_end 31
#define ____PARKED 0
#define ____CHARGE 61440
#define ____OFF 12288
#define ____REVERSE 48
#define ____FORWARD 240
#define ____SHUTDOWN_IMPENDING 3840
#define ____INIT 768

#define ERROR_PACKET_ID 1286
#define ERROR_PACKET_FREQ 2
#define __ERROR_start 0
#define __ERROR_end 19
#define ____LOST_VELOCITY_HEARTBEAT 0
#define ____LOST_PDM_YHEARTBEAT 240
#define ____LOST_BMS_HEARTBEAT 61440
#define ____LOST_THROTTLE_HEARTBEAT 3840
#define ____ERROR_NONE 983040

#define BRUSA_NLG5_STATUS_ID 1552
#define BRUSA_NLG5_STATUS_FREQ -1

#define BRUSA_NLG5_ACTUAL_VALUES_1_ID 1553
#define BRUSA_NLG5_ACTUAL_VALUES_1_FREQ -1

#define BRUSA_NLG5_ACTUAL_VALUES_2_ID 1554
#define BRUSA_NLG5_ACTUAL_VALUES_2_FREQ -1

#define BRUSA_NLG5_TEMP_FEEDBACK_ID 1555
#define BRUSA_NLG5_TEMP_FEEDBACK_FREQ -1

#define BRUSA_NLG5_ERROERS_ID 1556
#define BRUSA_NLG5_ERROERS_FREQ -1

#define BRUSA_NLG5_CONTROL_ID 1560
#define BRUSA_NLG5_CONTROL_FREQ -1

#define PDM_PACKET_ID 773
#define PDM_PACKET_FREQ 10
#define __LOW_VOLTAGE_BUS_BATTERY_FLAG_start 0
#define __LOW_VOLTAGE_BUS_BATTERY_FLAG_end 0
#define ____DOWN 0
#define ____UP 1
#define __LOW_VOLTAGE_DC-DC_STATUS_start 1
#define __LOW_VOLTAGE_DC-DC_STATUS_end 1
#define ____OFF 0
#define ____ON 1
#define __CRITICAL_SYSTEMS_BATTERY_FLAG_start 2
#define __CRITICAL_SYSTEMS_BATTERY_FLAG_end 2
#define ____DOWN 0
#define ____UP 1
#define __CRITICAL_SYSTEMS_DC-DC_STATUS_start 3
#define __CRITICAL_SYSTEMS_DC-DC_STATUS_end 3
#define ____OFF 0
#define ____ON 1

#define TRITIUM_BOOTLOADER_RESERVED4_ID 2036
#define TRITIUM_BOOTLOADER_RESERVED4_FREQ -1

#define TRITIUM_BOOTLOADER_RESERVED0_ID 2032
#define TRITIUM_BOOTLOADER_RESERVED0_FREQ -1

#define TRITIUM_BOOTLOADER_RESERVED1_ID 2033
#define TRITIUM_BOOTLOADER_RESERVED1_FREQ -1

#define TRITIUM_BOOTLOADER_RESERVED2_ID 2034
#define TRITIUM_BOOTLOADER_RESERVED2_FREQ -1

#define TRITIUM_BOOTLOADER_RESERVED3_ID 2035
#define TRITIUM_BOOTLOADER_RESERVED3_FREQ -1

#define PACK_CHARGE_ID 1780
#define PACK_CHARGE_FREQ 1
#define __CHARGE_AH_start 0
#define __CHARGE_AH_end 31
#define ____CHARGE_Ah 0
#define __CHARGE_PERCENTAGE_start 32
#define __CHARGE_PERCENTAGE_end 63
#define ____CHARGE_PERCENTAGE 0

#define PACK_CHARGE_MISBALANCE_ID 1781
#define PACK_CHARGE_MISBALANCE_FREQ 1
#define __BALANCE_SOC_start 0
#define __BALANCE_SOC_end 31
#define ____MISMATCH_CORRECTED_BALANCE_MISMATCH_Ah 0
#define __PACK_BALANCE_SOC_start 32
#define __PACK_BALANCE_SOC_end 63
#define ____CHARGE_PERCENTAGE_MISMATCH 0

#define CHARGING_CONTROL_INFO_ID 1782
#define CHARGING_CONTROL_INFO_FREQ 10
#define __CHARGING_CELL_VOLTAGE_ERROR_start 0
#define __CHARGING_CELL_VOLTAGE_ERROR_end 15
#define ____ERROR_mV_from 0
#define ____ERROR_mV_to 65535
#define __CELL_TEMP_MARGIN_start 16
#define __CELL_TEMP_MARGIN_end 31
#define ____CELL_TEMP_TENTH_C_from 0
#define ____CELL_TEMP_TENTH_C_to 65535
#define __DISCHARGING_CELL_VOLTAGE_ERROR_start 32
#define __DISCHARGING_CELL_VOLTAGE_ERROR_end 47
#define ____ERROR_mV_from 0
#define ____ERROR_mV_to 65535
#define __TOTAL_PACK_CAPACITY_start 48
#define __TOTAL_PACK_CAPACITY_end 63
#define ____CAPACITY_Ah_from 0
#define ____CAPACITY_Ah_to 65535

#define PRECHARGE_STATUS_ID 1783
#define PRECHARGE_STATUS_FREQ 1
#define __CONTACTOR_1_ERROR_start 0
#define __CONTACTOR_1_ERROR_end 0
#define ____OK 0
#define ____FAULT 1
#define __CONTACTOR_2_ERROR_start 1
#define __CONTACTOR_2_ERROR_end 1
#define ____OK 0
#define ____FAULT 1
#define __CONTACTOR_1_STATUS_start 2
#define __CONTACTOR_1_STATUS_end 2
#define ____OFF 0
#define ____ON 1
#define __CONTACTOR_2_STATUS_start 3
#define __CONTACTOR_2_STATUS_end 3
#define ____OFF 0
#define ____ON 1
#define __12V_CONTACTOR_STATUS_start 4
#define __12V_CONTACTOR_STATUS_end 4
#define ____FAULT 0
#define ____OK 1
#define __CONTACTOR_3_ERROR_start 5
#define __CONTACTOR_3_ERROR_end 5
#define ____OK 0
#define ____FAULT 1
#define __CONTACTOR_3_STATUS_start 6
#define __CONTACTOR_3_STATUS_end 6
#define ____OFF 0
#define ____ON 1
#define __PRECHARGE_STATE_start 7
#define __PRECHARGE_STATE_end 7

#define CELL_VOLTAGES_ID 1784
#define CELL_VOLTAGES_FREQ 10
#define __MIN_CELL_VOLTAGE_start 0
#define __MIN_CELL_VOLTAGE_end 15
#define ____VOLTAGE_mV_from 0
#define ____VOLTAGE_mV_to 65535
#define __MAX_CELL_VOLTAGE_start 16
#define __MAX_CELL_VOLTAGE_end 31
#define ____VOLTAGE_mV_from 0
#define ____VOLTAGE_mV_to 65535
#define __CMU_WITH_MIN_VOLTAGE_start 32
#define __CMU_WITH_MIN_VOLTAGE_end 39
#define ____CMU_NO_from 0
#define ____CMU_NO_to 255
#define __CELL_WITH_MIN_VOLTAGE_start 40
#define __CELL_WITH_MIN_VOLTAGE_end 47
#define ____CELL_NO_from 0
#define ____CELL_NO_to 255
#define __CMU_WITH_MAX_VOLTAGE_start 48
#define __CMU_WITH_MAX_VOLTAGE_end 55
#define ____CMU_NO_from 0
#define ____CMU_NO_to 255
#define __CELL_WITH_MAX_VOLTAGE_start 56
#define __CELL_WITH_MAX_VOLTAGE_end 63
#define ____CELL_NO_from 0
#define ____CELL_NO_to 255

#define CELL_TEMPS_ID 1785
#define CELL_TEMPS_FREQ 1
#define __MIN_CELL_TEMP_start 0
#define __MIN_CELL_TEMP_end 15
#define ____TEMP_TENTHS_C_from 0
#define ____TEMP_TENTHS_C_to 65535
#define __MAX_CELL_TEMP_start 16
#define __MAX_CELL_TEMP_end 31
#define ____TEMP_TENTHS_C_from 0
#define ____TEMP_TENTHS_C_to 65535
#define __CMU_WITH_MIN_TEMP_start 32
#define __CMU_WITH_MIN_TEMP_end 39
#define ____CMU_NO_from 0
#define ____CMU_NO_to 255
#define __CMU_WITH_MAX_TEMP_start 48
#define __CMU_WITH_MAX_TEMP_end 55
#define ____CMU_NO_from 0
#define ____CMU_NO_to 255

#define BATTERY_CURRENT_VOLTAGE_ID 1786
#define BATTERY_CURRENT_VOLTAGE_FREQ 10
#define __VOLTAGE_start 0
#define __VOLTAGE_end 31
#define ____VOLTAGE_mV_from 0
#define ____VOLTAGE_mV_to 4294967295
#define __CURRENT_start 32
#define __CURRENT_end 63
#define ____CURRENT_mA_from 0
#define ____CURRENT_mA_to 4294967295

#define OVERALL_PACK_STATUS_ID 1787
#define OVERALL_PACK_STATUS_FREQ 0
#define __BALANCE_VOLTAGE_THRESHOLD_RISING_start 0
#define __BALANCE_VOLTAGE_THRESHOLD_RISING_end 15
#define ____THRESHOLD_from 0
#define ____THRESHOLD_to 65535
#define __BALANCE_VOLTAGE_THRESHOLD_FALLING_start 16
#define __BALANCE_VOLTAGE_THRESHOLD_FALLING_end 31
#define ____THRESHOLD_from 0
#define ____THRESHOLD_to 65535
#define __CELL_OVER_VOLTAGE_start 32
#define __CELL_OVER_VOLTAGE_end 32
#define ____FALSE 0
#define ____TRUE 1
#define __CELL_UNDER_VOLTAGE_start 33
#define __CELL_UNDER_VOLTAGE_end 33
#define ____FALSE 0
#define ____TRUE 1
#define __CELL_OVER_TEMPERATURE_start 34
#define __CELL_OVER_TEMPERATURE_end 34
#define ____FALSE 0
#define ____TRUE 1
#define __MEASUREMENTS_UNTRUSTED_start 35
#define __MEASUREMENTS_UNTRUSTED_end 35
#define ____FALSE 0
#define ____TRUE 1
#define __CMU_COMMUNICATION_TIMEOUT_start 36
#define __CMU_COMMUNICATION_TIMEOUT_end 36
#define ____FALSE 0
#define ____TRUE 1
#define __VEHICLE_COMMUNICATIONS_TIMOUT_start 37
#define __VEHICLE_COMMUNICATIONS_TIMOUT_end 37
#define ____FALSE 0
#define ____TRUE 1
#define __BMS_SETUP_MODE_start 38
#define __BMS_SETUP_MODE_end 38
#define ____OFF 0
#define ____ON 1
#define __CMU_CAN_POWER_STATUS_start 39
#define __CMU_CAN_POWER_STATUS_end 39
#define ____OFF 0
#define ____ON 1
#define __CMU_COUNT_start 40
#define __CMU_COUNT_end 47
#define ____COUNT_from 0
#define ____COUNT_to 255
#define __FIRMWARE_BUILD_NO_start 48
#define __FIRMWARE_BUILD_NO_end 63
#define ____VERSION_from 0
#define ____VERSION_to 65535

#define FAN_INFO_ID 1788
#define FAN_INFO_FREQ 0
#define __FAN0_STATUS_start 0
#define __FAN0_STATUS_end 15
#define ____SPEED_RPM_from 0
#define ____SPEED_RPM_to 65535
#define __FAN1_STATUS_start 16
#define __FAN1_STATUS_end 31
#define ____SPEED_RPM_from 0
#define ____SPEED_RPM_to 65535
#define __FAN_AND_CONTACTOR_12V_CURRENT_CONSUMPTION_start 32
#define __FAN_AND_CONTACTOR_12V_CURRENT_CONSUMPTION_end 47
#define ____CONSUMPTION_mA_from 0
#define ____CONSUMPTION_mA_to 65535
#define __CMU_12V_CURRENT_CONSUMPTION_start 48
#define __CMU_12V_CURRENT_CONSUMPTION_end 63
#define ____CONSUMPTION_mA_from 0
#define ____CONSUMPTION_mA_to 65535

#define EXTENDED_PACK_STATUS_ID 1789
#define EXTENDED_PACK_STATUS_FREQ 0
#define __CELL_OVER_VOLTAGE_start 0
#define __CELL_OVER_VOLTAGE_end 0
#define ____FALSE 0
#define ____TRUE 1
#define __CELL_UNDER_VOLTAGE_start 1
#define __CELL_UNDER_VOLTAGE_end 1
#define ____FALSE 0
#define ____TRUE 1
#define __CELL_OVER_TEMPERATURE_start 2
#define __CELL_OVER_TEMPERATURE_end 2
#define ____FALSE 0
#define ____TRUE 1
#define __MEASUREMENTS_UNTRUSTED_start 3
#define __MEASUREMENTS_UNTRUSTED_end 3
#define ____FALSE 0
#define ____TRUE 1
#define __LOST_CMU_COMMUNICATION_start 4
#define __LOST_CMU_COMMUNICATION_end 4
#define ____FALSE 0
#define ____TRUE 1
#define __VEHICLE_COMMUNICATIONS_TIMOUT_start 5
#define __VEHICLE_COMMUNICATIONS_TIMOUT_end 5
#define ____FALSE 0
#define ____TRUE 1
#define __BMS_SETUP_MODE_start 6
#define __BMS_SETUP_MODE_end 6
#define ____OFF 0
#define ____ON 1
#define __CMU_CAN_POWER_STATUS_start 7
#define __CMU_CAN_POWER_STATUS_end 7
#define ____OFF 0
#define ____ON 1
#define __PACK_ISOLATION_TEST_FAILURE_start 8
#define __PACK_ISOLATION_TEST_FAILURE_end 8
#define ____FALSE 0
#define ____TRUE 1
#define __INVALID_SOC_MEASUREMENT_start 9
#define __INVALID_SOC_MEASUREMENT_end 9
#define ____FALSE 0
#define ____TRUE 1
#define __CAN_12V_SUPPLY_LOW_start 10
#define __CAN_12V_SUPPLY_LOW_end 10
#define ____FALSE 0
#define ____TRUE 1
#define __CONTACTOR_STUCK_start 11
#define __CONTACTOR_STUCK_end 11
#define ____FALSE 0
#define ____TRUE 1
#define __CMU_HAS_EXTRA_CELL_start 12
#define __CMU_HAS_EXTRA_CELL_end 12
#define ____FALSE 0
#define ____TRUE 1
#define __BMU_HARDWARE_VERSION_start 32
#define __BMU_HARDWARE_VERSION_end 39
#define ____NO_from 0
#define ____NO_to 255
#define __BMU_HARDWARE_MODEL_start 40
#define __BMU_HARDWARE_MODEL_end 47
#define ____NO_from 0
#define ____NO_to 255

#define TRITIUM_UNUSED_RESERVED0_ID 1790
#define TRITIUM_UNUSED_RESERVED0_FREQ -1

#define TRITIUM_UNUSED_RESERVED1_ID 1791
#define TRITIUM_UNUSED_RESERVED1_FREQ -1

